name: Notificación de PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Añadir comentario
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `Nuevo PR creado por @${context.payload.pull_request.user.login}: ${context.payload.pull_request.html_url}`
            })